# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-14 12:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150L)),
                ('content', models.TextField(blank=True)),
            ],
            options={
                'db_table': 't_about',
                'verbose_name': 'about',
                'verbose_name_plural': 'about',
            },
        ),
        migrations.CreateModel(
            name='AboutCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catname', models.CharField(blank=True, max_length=150L)),
            ],
            options={
                'db_table': 't_about_category',
                'verbose_name': 'about_category',
                'verbose_name_plural': 'about_category',
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100L, verbose_name=b'Title')),
                ('content', models.TextField(verbose_name=b'Content')),
                ('createddate', models.DateField(blank=True, db_column=b'createdDate', default=b'2017-10-14', null=True, verbose_name=b'Date')),
            ],
            options={
                'db_table': 't_announcement',
                'verbose_name': 'announcement',
                'verbose_name_plural': 'announcement',
            },
        ),
        migrations.CreateModel(
            name='Download',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150L)),
                ('content', models.TextField(blank=True)),
                ('downloadurl', models.CharField(blank=True, max_length=200L)),
                ('createddate', models.DateField(blank=True, db_column=b'createdDate', null=True)),
            ],
            options={
                'db_table': 't_download',
                'verbose_name': 'download',
                'verbose_name_plural': 'download',
            },
        ),
        migrations.CreateModel(
            name='DownloadCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catname', models.CharField(blank=True, max_length=150L)),
            ],
            options={
                'db_table': 't_download_category',
                'verbose_name': 'download_category',
                'verbose_name_plural': 'download_category',
            },
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150L, verbose_name=b'title')),
                ('content', models.TextField(blank=True, verbose_name=b'content')),
            ],
            options={
                'db_table': 't_faq',
                'verbose_name': 'faq',
                'verbose_name_plural': 'faq',
            },
        ),
        migrations.CreateModel(
            name='FaqCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catname', models.CharField(blank=True, max_length=150L)),
            ],
            options={
                'db_table': 't_faq_category',
                'verbose_name': 'faq_category',
                'verbose_name_plural': 'faq_category',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255L, verbose_name=b'Title')),
                ('content', models.TextField(blank=True, verbose_name=b'Content')),
                ('createddate', models.DateField(blank=True, db_column=b'createdDate', default=b'2017-10-14', null=True, verbose_name=b'Created Date')),
            ],
            options={
                'db_table': 't_news',
                'verbose_name': 'news',
                'verbose_name_plural': 'news',
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catname', models.CharField(blank=True, max_length=150L)),
            ],
            options={
                'db_table': 't_product_category',
                'verbose_name': 'product_category',
                'verbose_name_plural': 'product_category',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200L, verbose_name=b'Name')),
                ('product_simple_desc', models.TextField(blank=True, verbose_name=b'Simple Desc')),
                ('product_full_desc', models.TextField(blank=True, verbose_name=b'Full Desc')),
                ('product_pic', models.CharField(blank=True, max_length=200L, verbose_name=b'Picture Path')),
                ('product_order', models.IntegerField(verbose_name=b'Order')),
                ('createddate', models.DateField(blank=True, db_column=b'createdDate', default=b'2017-10-14', verbose_name=b'Created Date')),
                ('catid', models.ForeignKey(db_column=b'catid', on_delete=django.db.models.deletion.CASCADE, to='app1.ProductCategory', verbose_name=b'catid')),
            ],
            options={
                'db_table': 't_products',
                'verbose_name': 'products',
                'verbose_name_plural': 'products',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150L)),
                ('content', models.TextField(blank=True)),
            ],
            options={
                'db_table': 't_service',
                'verbose_name': 'service',
                'verbose_name_plural': 'service',
            },
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catname', models.CharField(blank=True, max_length=150L)),
            ],
            options={
                'db_table': 't_service_category',
                'verbose_name': 'service_category',
                'verbose_name_plural': 'service_category',
            },
        ),
        migrations.AddField(
            model_name='service',
            name='catid',
            field=models.ForeignKey(db_column=b'catid', on_delete=django.db.models.deletion.CASCADE, to='app1.ServiceCategory', verbose_name=b'catid'),
        ),
        migrations.AddField(
            model_name='faq',
            name='catid',
            field=models.ForeignKey(db_column=b'catid', on_delete=django.db.models.deletion.CASCADE, to='app1.FaqCategory', verbose_name=b'catid'),
        ),
        migrations.AddField(
            model_name='download',
            name='catid',
            field=models.ForeignKey(db_column=b'catid', on_delete=django.db.models.deletion.CASCADE, to='app1.DownloadCategory', verbose_name=b'catid'),
        ),
        migrations.AddField(
            model_name='about',
            name='catid',
            field=models.ForeignKey(db_column=b'catid', on_delete=django.db.models.deletion.CASCADE, to='app1.AboutCategory', verbose_name=b'catid'),
        ),
    ]
